### ISSUE TITLE
Port docker build workflow to github

### ISSUE THREAD

**Issue by glemieux** [NGEET/tutorial-containers#13]
```[tasklist]
### Tasks
- [x] Setup docker secret keys
- [ ] https://github.com/NGEET/tutorial-containers/issues/16
- [ ] https://github.com/NGEET/tutorial-containers/issues/15
- [ ] https://github.com/NGEET/tutorial-containers/issues/14
- [ ] https://github.com/NGEET/tutorial-containers/issues/17
- [ ] Develop pull request testing methodology
```

**Comment by glemieux** [comment]
What particularly behavior do we want to test within each container, particularly for containers that build on each other?  Should testing be conducted only for pull requests or also for merges to main?

baseos:
- test build elm-fates dockerfile off of new image
- test tooling (e.g. `nco` package, python `scipy` and `netcdf4` installs)
- test applications built from source (xml parser, hdf5, netcdf, openMPI)

elm-fates:
- can we build a simple single site case (see e3sm testing for examples to adopt)

jupyter:
- minimum exercises for installed packages

**Comment by glemieux** [comment]
- [ ] Question: do docker hooks affect the github image build?
- [ ] Review how the docker buildx action works

**Comment by glemieux** [comment]
- [ ] Q: review how the buildx action config works.

**Comment by glemieux** [comment]
Note that the docker actions currently don't work with the `macos-14` github arm64 runners: see https://github.com/docker/actions-toolkit/issues/317.  It might be possible to use the "large" linux arm runners, but those are only available to Github Team or Enterprise plans: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/running-jobs-on-larger-runners.  

Given the above, until this rolls out for more plans or hardware virtualization is provided for the `macos` arm runners, this will have to be build with docker's platform emulation.
