### ISSUE TITLE
baseos docker image build workflow

### ISSUE THREAD

**Issue by glemieux** [NGEET/tutorial-containers#15]
```[tasklist]
### Tasks
- [x] Develop amd64 build version
- [x] Develop arm64 build version
```

**Comment by glemieux** [comment]
Testing the baseos image by trying to generate a known working upstream (e.g. elm-fates) image build process would require building the elm-fates using the `main` branch of the repository.

For a pull request, it might be useful to load the image to a local registry instead of pushing to the official dockerhub registry.  See here: https://docs.docker.com/build/ci/github-actions/local-registry/.  As such, the build would only be pushed if it passed tests and was merged to `main`.  This means that any changes to main should really be merged into the pull request branch during testing, which would need to be automated.

**Comment by glemieux** [comment]
Using the official docker platform emulation via github works and doesn't seem to struggle with #12 currently.  The build does take a long time, which is not unexpected given emulation + building multiple packages from source, so it would be good to figure out how to leverage existing build layers to reduce future update build times.

- [ ] Review if github build will pull from pre-existing image or if uploading artefact is necessary
- [ ] Review cache options

**Comment by glemieux** [comment]
Moving testing tasks to a new issue to be addressed via a different pull request: #19
