### ISSUE TITLE
baseos image testing workflow

### ISSUE THREAD

**Issue by glemieux** [NGEET/tutorial-containers#19]
```[tasklist]
### Tasks
- [ ] Add upstream elm-fates build off of newly created image
- [ ] Add python package testing
- [ ] Add nco tool testing
- [ ] Add testing for installed from source packages (HDF5, netcdf, XML parser, openMPI)
```
